language: python
python:
  - "3.4"
virtualenv: system_site_packages: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "travis-retry sudo apt-get install python3-pyside"
script: py.test -s
