language: python
python:
  - "3.4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install libqt4-dev
  - pip install wheelhouse/PySide-1.2.2-cp34-cp34m-linux_x86_64.whl
   # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
script: tox -e py34-pyside,py34-flake8
cache:
  directories:
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
