language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Cached Downloads
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - if [ ! -f /downloads/sip.tar.gz ];   then curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz; fi
  - if [ ! -f /downloads/pyqt4.tar.gz ]; then curl -L -o /downloads/pyqt4.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz; fi
  - if [ ! -f /downloads/pyqt5.tar.gz ]; then curl -L -o /downloads/pyqt5.tar.gz https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.9/PyQt5_gpl-5.9.tar.gz; fi
  - echo '6d01ea966a53e4c7ae5c5e48c40e49e5  /downloads/sip.tar.gz' | md5sum -c -
  - echo '997c3e443165a89a559e0d96b061bf70  /downloads/pyqt4.tar.gz' | md5sum -c -
  - echo 'a409ac0d65ead9178b90c2822759a84b  /downloads/pyqt5.tar.gz' | md5sum -c -
  # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds
install:
  # Qt4
  - sudo apt-get install -y libqt4-dev
  # Qt5
  - sudo add-apt-repository -y ppa:beineri/opt-qt59-trusty
  - sudo apt-get update
  - sudo apt-get install -y qt59base
  # Builds
  - pushd /builds
  # SIP
  - tar xzf /downloads/sip.tar.gz --keep-newer-files
  - pushd sip-4.16.5
  - python configure.py
  - make
  - sudo make install
  - popd
  # PyQt4
  - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
  - pushd PyQt-x11-gpl-4.11.3
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui
  - make
  - sudo make install
  - popd
  # PyQt5
  - source /opt/qt59/bin/qt59-env.sh  # switch to Qt5
  - tar xzf /downloads/pyqt5.tar.gz --keep-newer-files
  - pushd PyQt5_gpl-5.9
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtWidgets
  - make
  - sudo make install
  - popd
  # Builds Complete
  - popd
  # PySide
  - if [ $TRAVIS_PYTHON_VERSION != '3.5' && $TRAVIS_PYTHON_VERSION != '3.6' ]; then pip install --find-links wheelhouse/ pyside; fi
  # Python 3.3
  - if echo $TRAVIS_PYTHON_VERSION | grep -q '^3.3'; then pip install asyncio; fi
  # flake8 style checker
  - pip install flake8 pep8-naming flake8-debugger flake8-docstrings pytest-timeout
script:
  - flake8
  - flake8 --select=D1 quamash/*.py
  - if [ $TRAVIS_PYTHON_VERSION != '3.5' && $TRAVIS_PYTHON_VERSION != '3.6']; then QUAMASH_QTIMPL=PySide py.test; fi
  - QUAMASH_QTIMPL=PyQt4 py.test
  - QUAMASH_QTIMPL=PyQt5 py.test
cache:
  directories:
    - /downloads
  apt: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ed6fa8828890c4a49ea
    on_success: change
    on_failure: always
    on_start: false
