language: python
python:
  - "3.4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "pip install wheelhouse/PySide-1.2.2-cp34-cp34m-linux_x86_64.whl pytest-pep8 pytest-cov pytest-flakes"
script: py.test
cache:
  directories:
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
