language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install -y libqt4-dev
  - pip install --find-links wheelhouse/ pyside
  - python `which pyside_postinstall.py` -install
  - if echo $TRAVIS_PYTHON_VERSION | grep -q '^3.3'; then pip install asyncio; fi
script: py.test
cache:
  directories:
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
